# Generated by Django 5.0.2 on 2024-02-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
